# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_bias_act <- function(x, b, xref, yref, dy, grad, dim, act, alpha, gain, clamp) {
    .Call('_styleganr_cpp_bias_act', PACKAGE = 'styleganr', x, b, xref, yref, dy, grad, dim, act, alpha, gain, clamp)
}

