# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:

  Build-Libs:

    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '#build-libs')
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: macOS-latest,
              cuda: 0,
              cmakevars: ,
            }
          - {
              os: windows-2019,
              cuda: 0,
              cmakevars: ,
            }
          - {
              os: windows-2019,
              cuda: "11.3",
              cuda_patch: "1",
              cmakevars: '-DCUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.3"',
              cudnn: "https://storage.googleapis.com/torch-lantern-builds/cudnn/cudnn-11.3-windows-x64-v8.2.1.32.zip",
            }
          - {
              os: ubuntu-20.04,
              cuda: 0,
              cmakevars: ,
            }
          - {
              os: ubuntu-20.04,
              cuda: "11.3",
              cuda_patch: "1",
              cudnn: "https://storage.googleapis.com/torch-lantern-builds/cudnn/cudnn-11.3-linux-x64-v8.2.1.32.tgz",
            }
          - {
              os: ubuntu-20.04,
              cuda: "11.6",
              cuda_patch: "1",
              cmakevars: ,
              cudnn: "https://storage.googleapis.com/torch-lantern-builds/cudnn/cudnn-linux-x86_64-8.6.0.163_cuda11-archive.tgz",
            }
            
    env:
      TORCH_INSTALL: 1
      INSTALL_TORCH: 1
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Create environment
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: Free up 24GB of disk space
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: sudo rm -rf /usr/share/dotnet
      - name: Install CUDA
        if: ${{matrix.config.cuda != ''}}
        uses: Jimver/cuda-toolkit@v0.2.7
        id: cuda-toolkit
        with:
          cuda: "${{matrix.config.cuda}}.${{matrix.config.cuda_patch}}"

      - name: Install cuDNN (Linux)
        if: ${{ matrix.config.cuda != '' && contains(matrix.config.os, 'ubuntu') }}
        run: |
          find $CUDA_PATH -maxdepth 2 -type d -ls
          wget --quiet ${{matrix.config.cudnn}} -O cudnn.tgz
          tar -xzvf cudnn.tgz
          sudo cp cuda/include/cudnn*.h $CUDA_PATH/include
          sudo cp cuda/lib64/libcudnn* $CUDA_PATH/lib64 2>/dev/null || :
          sudo cp cuda/lib/libcudnn* $CUDA_PATH/lib64 2>/dev/null || :
          sudo chmod a+r $CUDA_PATH/include/cudnn*.h $CUDA_PATH/lib64/libcudnn* 2>/dev/null || :
          sudo chmod a+r $CUDA_PATH/include/cudnn*.h $CUDA_PATH/lib/libcudnn* 2>/dev/null || :
          ls $CUDA_PATH/lib/ || true
          ls $CUDA_PATH/lib64/ || true
          rm cudnn.tgz
          find $CUDA_PATH -maxdepth 2 -type d -ls
          echo "CUDA=${{matrix.config.cuda}}" >> $GITHUB_ENV
      - name: Install cuDNN (Windows)
        if: ${{ matrix.config.cuda != '' && contains(matrix.config.os, 'windows') }}
        run: |
          curl ${{ matrix.config.cudnn }} --output cudnn.zip --silent --location
          Expand-Archive -Path cudnn.zip -DestinationPath "C:\cudnn"
          Get-ChildItem -Path "C:\cudnn"
          Get-ChildItem -Path "${env:CUDA_PATH}"
          Move-Item -Path "C:\cudnn\cuda\bin\cudnn*.dll" -Destination "${env:CUDA_PATH}\bin"
          Move-Item -Path "C:\cudnn\cuda\include\cudnn*.h" -Destination "${env:CUDA_PATH}\include"
          Move-Item -Path "C:\cudnn\cuda\lib\x64\cudnn*.lib" -Destination "${env:CUDA_PATH}\lib\x64"
          echo "CUDNN_INCLUDE_PATH=""${CUDA_PATH}\include""" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "CUDNN_LIBRARY_PATH=""${CUDA_PATH}\lib\x64""" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "CUDA=${{ matrix.config.cuda }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          http-user-agent: ${{ matrix.http-user-agent }}
          use-public-rspm: true

      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes', 'desc', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE, INSTALL_opts='--no-multiarch')"

      - run: |
          cd csrc
          mkdir build && cd build
          cmake ${{ matrix.cmakevars }} ..
          cmake --build . --target package --config Release

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: csrc/build/*.zip
          overwrite: true
          file_glob: true
          tag: libstyleganr


  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: '3.6'}
          - {os: ubuntu-18.04,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      TORCH_INSTALL: 1

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true


      - run: |
          Rscript -e "install.packages(c('remotes', 'desc', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE, INSTALL_opts='--no-multiarch')"

      - run: |
          cd csrc
          mkdir build && cd build
          cmake ..
          cmake --build . --target package --config Release
          cmake --install .
          Rscript -e "cat('ZIP file:', normalizePath(list.files(pattern='zip', full.names=TRUE)))"
          Rscript -e "cat('ENV file:', Sys.getenv('GITHUB_ENV'))"
          Rscript -e "writeLines(paste0('STYLEGANR_URL=',normalizePath(list.files(pattern='zip', full.names=TRUE))), Sys.getenv('GITHUB_ENV'))"

      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
          args: 'c("--no-multiarch", "--no-manual")'

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
